import { Button, ButtonGroup, Card, Container, Heading } from "@chakra-ui/react"
import styles from "./index.module.css"
import { type NextPage } from "next"
import Head from "next/head"
import { env } from "~/env.mjs"
import { useRouter } from "next/router"
import axios from "axios"

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Admin APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <Card p={4}>
          <Heading>Mis ventas</Heading>
          <ButtonGroup mt={8}>
            <Button
              colorScheme="blue"
              onClick={() => {
                router.push("/login")
              }}
            >
              Iniciar sesión
            </Button>

            <Button
              colorScheme="purple"
              onClick={() => {
                router.push("/clients")
              }}
            >
              Clientes
            </Button>
          </ButtonGroup>
        </Card>
      </Container>
    </>
  )
}

export default Home
