import { Button } from "@chakra-ui/react"
import styles from "./index.module.css"
import { type NextPage } from "next"
import Head from "next/head"
import { env } from "~/env.mjs"
import { useRouter } from "next/router"

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Admin APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>{env.NEXT_PUBLIC_BACKEND_BASE_URL}</h1>
        </div>
        <Button
          colorScheme="blue"
          onClick={() => {
            router.push("/login")
          }}
        >
          Button
        </Button>
      </main>
    </>
  )
}

export default Home
