import { Button, ButtonGroup, Container, Heading } from "@chakra-ui/react"
import styles from "./index.module.css"
import { type NextPage } from "next"
import Head from "next/head"
import { env } from "~/env.mjs"
import { useRouter } from "next/router"
import axios from "axios"

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Admin APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <Heading>Mis ventas</Heading>
        <ButtonGroup>
          <Button
            colorScheme="blue"
            onClick={() => {
              router.push("/login")
            }}
          >
            Iniciar sesión
          </Button>
          <Button
            colorScheme="green"
            onClick={() => {
              axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
                withCredentials: true,
              })
            }}
          >
            Get sales
          </Button>
          <Button
            colorScheme="purple"
            onClick={() => {
              axios.post(
                `${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`,
                {
                  operation_date: new Date(),
                  total_amount: 2500,
                },
                {
                  withCredentials: true,
                }
              )
            }}
          >
            Create sale
          </Button>
        </ButtonGroup>
      </Container>
    </>
  )
}

export default Home
